### ISSUE TITLE
Need to ensure that when Akka.Cluster node exits, Web API gets shutdown

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/Petabridge.App.Web#67]
We don't want to create any zombie ASP.NET instances where the `ActorSystem` that the application relies on is terminated, but the app is still running. Need to ensure that when `ActorSystem.WhenTerminated.IsComplete` is true the `IHost` also terminates.

**Comment by eaba** [comment]
##Proposed `AkkaService` changes

## Inject `IHostApplicationLifetime` via `AkkaService`.ctor
```csharp
private readonly IHostApplicationLifetime _applicationLifetime;
public AkkaService(IServiceProvider serviceProvider, IHostApplicationLifetime appLifetime)
{
        _serviceProvider = serviceProvider;
        _applicationLifetime = appLifetime;
}
```

## update `StartAsync'
```csharp
// add a continuation task that will guarantee 
// shutdown of application if ActorSystem terminates first
 ClusterSystem.WhenTerminated.ContinueWith(tr => {
   _applicationLifetime.StopApplication();
});
.......
```

**Comment by Aaronontheweb** [comment]
Yep, that's a good solution @eaba
