### ISSUE TITLE
Update proposal

### ISSUE THREAD

**Issue by eaba** [petabridge/Petabridge.App.Web#95]
* [x] Replace `common.props` with `Directory.Build.props`. `Directory.Build.props` is automatically imported during build.  [#100] 
* [x] Update `NetCoreFramework` to .NET 6 [#101]
* [x] Update `Microsoft.NET.Test.Sdk` to `17.0.0`
* [x] Update `AkkaVersion` to `1.4.31`
* [x] Fix https://github.com/petabridge/Petabridge.App.Web/pull/91
* [ ] Nuke Build support

**Comment by Aaronontheweb** [comment]
Do we want to look at Github Actions as a replacement for AzDo?
