### ISSUE TITLE
Nuke Build support

### ISSUE THREAD

**Issue by eaba** [petabridge/Petabridge.App.Web#99]
![image](https://user-images.githubusercontent.com/8049896/148911602-45a37e6f-438f-4fd5-af0c-08924acd27ff.png)

## 1. The cross-platform build automation solution for .NET with C# DSL
What this mean is C# developer can start automating builds almost immediately. With FAKE, aside learning how to use it, there is also the burden of having to learn F# first.

![image](https://user-images.githubusercontent.com/8049896/148913257-d67e7881-ea9b-4b5f-a418-08b733490f0b.png)

## 2. Overcoming YAML hell

NUKE can generates the CI configuration from the C# build implementation itself

![image](https://user-images.githubusercontent.com/8049896/148913885-28de03a5-62af-48da-a49f-a0a6c9364071.png)

**Comment by Aaronontheweb** [comment]
Ok, I'm interested - can you implement this in a PR and show me the YAML you generated? That sounds very cool.

**Comment by eaba** [comment]
Sure!

**Comment by eaba** [comment]
From this in `Fake`:
```fsharp
/--------------------------------------------------------------------------------
// Documentation 
//--------------------------------------------------------------------------------  
Target "DocFx" (fun _ ->
    DotNetCli.Restore (fun p -> { p with Project = solutionFile })
    DotNetCli.Build (fun p -> { p with Project = solutionFile; Configuration = configuration })

    let docsPath = "./docs"

    DocFx (fun p -> 
                { p with 
                    Timeout = TimeSpan.FromMinutes 30.0; 
                    WorkingDirectory  = docsPath; 
                    DocFxJson = docsPath @@ "docfx.json" })
)

```
To this in `Nuke`:
```csharp

    Target BuildDocs => _ => _
        .DependsOn(Restore)
        .DependsOn(Compile)
        .Executes(() => 
        {
            var docsPath = "./docs";
             //Nuke.Common.Tools.DocFX.DocFXTasks;
            DocFX($"build {docsPath}/docfx.json", workingDirectory: docsPath, timeout: TimeSpan.FromMinutes(30).Minutes);
        });
```

**Comment by Aaronontheweb** [comment]
Ok, try porting the whole thing

**Comment by Aaronontheweb** [comment]
Aha https://github.com/petabridge/Petabridge.App.Web/pull/103
